services:
  podfolio:
    image: podfolio:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: podfolio
      DB_USERNAME: podfolio
      DB_PASSWORD: podfolio
    volumes:
      - ".:/var/www/html"

  db:
    image: mariadb:latest
    container_name: podfolio_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: somethingsecure
      MARIADB_DATABASE: podfolio
      MARIADB_USER: podfolio
      MARIADB_PASSWORD: podfolio
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  db_data:
